5.0.0
Iconica-Development/flutter_timeline pull request #99
Opened 2024-08-01 11:39 UTC by mighttymike

2024-08-08 08:41 UTC, Gorter-dev requested changes

2024-08-08 08:41 UTC, Gorter-dev commented on packages/flutter_timeline/CHANGELOG.md
Make this an actual symbolic link

2024-08-08 08:41 UTC, Gorter-dev commented on packages/flutter_timeline/README.md
Make this an actual symbolic link

2024-08-08 08:41 UTC, Gorter-dev commented on packages/flutter_timeline/LICENSE
Make this an actual symbolic link

2024-08-08 08:41 UTC, Gorter-dev commented on packages/flutter_timeline_firebase/CHANGELOG.md
Make this an actual symbolic link

2024-08-08 08:41 UTC, Gorter-dev commented on packages/flutter_timeline_firebase/LICENSE
Make this an actual symbolic link

2024-08-08 08:41 UTC, Gorter-dev commented on packages/flutter_timeline_firebase/README.md
Make this an actual symbolic link

2024-08-08 08:41 UTC, Gorter-dev commented on packages/flutter_timeline_interface/CHANGELOG.md
Make this an actual symbolic link

2024-08-08 08:41 UTC, Gorter-dev commented on packages/flutter_timeline_interface/LICENSE
Make this an actual symbolic link

2024-08-08 08:41 UTC, Gorter-dev commented on packages/flutter_timeline_interface/README.md
Make this an actual symbolic link

2024-08-08 08:41 UTC, Gorter-dev commented on packages/flutter_timeline_view/CHANGELOG.md
Make this an actual symbolic link

2024-08-08 08:41 UTC, Gorter-dev commented on packages/flutter_timeline_view/LICENSE
Make this an actual symbolic link

2024-08-08 08:41 UTC, Gorter-dev commented on packages/flutter_timeline_view/README.md
Make this an actual symbolic link

2024-08-23 07:11 UTC, freekvandeven requested changes

2024-08-23 07:11 UTC, freekvandeven commented on .github/workflows/melos-component-ci.yml
i prefer you not specify it unless the newest version is breaking the package

2024-08-23 13:37 UTC, freekvandeven approved these changes

2024-09-02 12:22 UTC, freekvandeven requested changes

2024-09-02 12:22 UTC, freekvandeven commented on packages/flutter_timeline_view/pubspec.yaml
> +version: 5.1.0
you should make it 5.0.0

2024-09-05 09:13 UTC, Gorter-dev approved these changes

2024-09-05 09:15 UTC, merged